### ISSUE TITLE
kotlin-sdk-server 0.10.0 crashes with NoSuchMethodError when used with Ktor 3.4.x

### ISSUE THREAD

**Issue by MaXal** [modelcontextprotocol/kotlin-sdk#666]
**Describe the bug**
`NoSuchMethodError` at runtime when using kotlin-sdk-server:0.10.0 with Ktor 3.4.x. The SDK's mcp() extension calls sse(Route, Function2) which no longer exists in ktor-server-sse:3.4.x (SSE routing API signature changed). The SDK declares ktor-server-sse:3.2.3, but Gradle resolves to the consumer's higher 3.4.x version, causing binary incompatibility.

**To Reproduce**
1. Add `io.modelcontextprotocol:kotlin-sdk-server:0.10.0` and `io.ktor:ktor-server-sse:3.4.2` to dependencies
2. Call `mcp { ... }` inside a Ktor `embeddedServer` block
3. Start the server

**Expected behavior**
The MCP server starts without errors, or the SDK documents the supported Ktor version range.

**Logs**
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void io.ktor.server.sse.RoutingKt.sse(io.ktor.server.routing.Route, kotlin.jvm.functions.Function2)'
      at io.modelcontextprotocol.kotlin.sdk.server.KtorServerKt.mcp(KtorServer.kt:75)
```

**Additional context**
Works fine on Ktor 3.3.3.

**Comment by rnett** [comment]
Also encountered this, I'm somewhat surprised the sdk is using that old of a ktor version.

It's also a bit annoying that ktor broke binary compatibility in a minor release.

**Comment by kpavlov** [comment]
See #608 
0.11.0 includes #611 with 3.3.3

**Comment by devcrocod** [comment]
> Also countered this, I'm somewhat surprised the sdk is using that old of a ktor version.

The reason we are not upgrading to the latest ktor versions is compatibility. In release 0.11.0, we updated Ktor to 3.3.3, but compatibility was broken in ktor 3.4, so this issue is still relevant.

I've already reported this compatibility issue to the Ktor team
